openapi: 3.0.1
info:
  title: Cotización de Divisas API
  description: API para obtener cotizaciones de monedas
  contact:
    name: Cecilia Godoy
    email: cecilia.godoy@familiar.com.py
  version: 1.0.0
servers:
  - url: https://api.example.com/v1
    description: Servidor principal (producción)
  - url: https://staging-api.example.com
    description: Servidor interno de pruebas
paths:
  /cotizacion/{moneda-origen}:
    get:
      summary: Cotizaciones por moneda origen
      description: Obtiene las cotizaciones para una moneda de origen específica
      parameters:
        - name: moneda-origen
          in: path
          description: Moneda origen (por ejemplo, GS)
          required: true
          schema:
            type: string
        - name: fecha
          in: query
          description: filtro por fecha del cambio. Por defecto es la cotización del día
          required: false
          schema:
            type: string
      responses:
        '200':
          $ref: '#/components/responses/MonedaListar'
        '400':
          $ref: './familiar-components.yaml#/components/responses/BadRequest'
        '401':
          $ref: './familiar-components.yaml#/components/responses/Unauthorized'
        '403':
          $ref: './familiar-components.yaml#/components/responses/Forbidden'
        '404':
          $ref: './familiar-components.yaml#/components/responses/NotFound'
        '429':
          $ref: './familiar-components.yaml#/components/responses/TooManyRequests'
        '500':
          $ref: './familiar-components.yaml#/components/responses/InternalServerError'

  /cotizacion/{moneda-origen}/sucursales/{sucursal}:
    get:
      summary: Obtiene las cotizaciones para una moneda de origen específica
      parameters:
        - name: moneda-origen
          in: path
          required: true
          description: Código de la moneda de origen (por ejemplo, PYG)
          schema:
            type: string
        - name: sucursal
          in: path
          required: true
          description: nombre de la sucursal
          schema:
            type: string
        - name: fecha
          in: query
          description: filtro por fecha del cambio. Por defecto es la cotización del día
          required: false
          schema:
            type: string
      responses:
        '200':
          $ref: '#/components/responses/Sucursales'
        '400':
          $ref: './familiar-components.yaml#/components/responses/BadRequest'
        '401':
          $ref: './familiar-components.yaml#/components/responses/Unauthorized'
        '403':
          $ref: './familiar-components.yaml#/components/responses/Forbidden'
        '404':
          $ref: './familiar-components.yaml#/components/responses/NotFound'
        '429':
          $ref: './familiar-components.yaml#/components/responses/TooManyRequests'
        '500':
          $ref: './familiar-components.yaml#/components/responses/InternalServerError'

  /cotizacion/{moneda-origen}/sucursales/{sucursal}/monedas/{codigo-moneda}:
    get:
      summary: Obtiene las cotizaciones para una moneda de origen específica
      parameters:
        - name: moneda-origen
          in: path
          required: true
          description: Código de la moneda de origen (por ejemplo, PYG)
          schema:
            type: string
        - name: sucursal
          in: path
          required: true
          description: nombre de la sucursal
          schema:
            type: string
        - name: codigo-moneda
          in: path
          required: true
          description: nombre de la sucursal
          schema:
            type: string
        - name: fecha
          in: query
          description: filtro por fecha del cambio. Por defecto es la cotización del día
          required: false
          schema:
            type: string
      responses:
        '200':
          $ref: '#/components/responses/Moneda'
        '400':
          $ref: './familiar-components.yaml#/components/responses/BadRequest'
        '401':
          $ref: './familiar-components.yaml#/components/responses/Unauthorized'
        '403':
          $ref: './familiar-components.yaml#/components/responses/Forbidden'
        '404':
          $ref: './familiar-components.yaml#/components/responses/NotFound'
        '429':
          $ref: './familiar-components.yaml#/components/responses/TooManyRequests'
        '500':
          $ref: './familiar-components.yaml#/components/responses/InternalServerError'


  '/cotizacion/{codigo-cliente}/prepactada':
    get:
      summary: Obtiene las tasas de cambio prepactada de un cliente
      description: Devuelve las tasas de cambio prepactada de un cliente
      parameters:
        - $ref: './familiar-components.yaml#/components/parameters/codigo-cliente'

      responses:
        '200':
          description: Respuesta exitosa
          content:
            application/json:
              schema:
                type: object
                properties:
                  codOperacion:
                    type: string

components:
  schemas:
    Cotizaciones:
      type: object
      properties:
        cotizacion:
          type: array 
          items: 
            $ref: '#/components/schemas/Moneda'

    Moneda:
      allOf:
        - $ref: './familiar-components.yaml#/components/schemas/accountcurrency'
        - type: object
          properties:
            compra:
              type: number
            venta:
              type: number

    Sucursales:
      type: object
      properties:
        nombreSucursal:
          type: string
        cotizaciones:
          type: array 
          items: 
            $ref: '#/components/schemas/Moneda'

    Pizarra:
      type: object
      properties:
        monedaOrigen:
          type: string
        fecha:
          type: string
        sucursales:
          type: array 
          items: 
            $ref: '#/components/schemas/Sucursales'

  responses:
    MonedaListar:
      description: Moneda
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Pizarra'
    Sucursal:
      description: sucursal
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Sucursales'

    Moneda:
      description: sucursal
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Moneda'   
    