openapi: 3.0.1
info:
  title: Clientes
  description: 'Este servicio obtiene datos relacioandos al Clientes, sus productos y servicios, movimientos y configuracion relacionada al cliente'
  contact:
    name: Cecilia Godoy
    email: cecilia.godoy@familiar.com.py
  version: 1.0.0
servers:
  - url: https://localhost/clientes/v1
security:
  - default: []    
paths:
  '/clientes/{codigo-cliente}/productos/cuentas':
    get:
      tags:
        - cuentas
        - clientes
        - List
      summary: Obtener lista de cuentas de un cliente
      description: Obtener informacion sobre todas las cuentas del clientes. Cajas de ahorro, cuentas corrientes, cuentas digitales, etc.
      operationId: getall
      parameters:
        - $ref: './familiar-components-v1.0.0.yaml#/components/parameters/codigo-cliente'
      responses:
        '200':
          description: 'Respuesta Varias cuentas'
          content:
            application/json:
              schema:
                $ref: '#/components/responses/CuentaListarResponse'
              examples:
                example:
                  value: '[{"estadoCuenta":{"estado":{"codigo":"AC","valor":"Activo","fecha":null},"tipoEstado":"Activa"},"identificacion":{"tipoIdentificadorCuenta":"NumeroCuenta","identificacion":{"codigo":"81-25","valor":"José Samaniego","fechaEmision":null,"fechaVencimiento":null}},"fecha":{"tipo":"FechaApertura","fecha":"04-01-2023"},"relacion":{"codigo":"E","valor":"Empresa","fecha":null},"producto":{"tipo":"CuentaCorriente","nombre":"Cuenta Corriente","codigo":"101"},"moneda":{"id":"GS","codigo":"6900"},"balance":{"saldos":[{"monto":null,"saldo":"5000000","tipo":"SaldoDisponible","fecha":null,"indicador":null},{"monto":null,"saldo":"5000000","tipo":"SaldoRetenido","fecha":null,"indicador":null},{"monto":null,"saldo":"5000000","tipo":"SaldoActual","fecha":null,"indicador":null},{"monto":null,"saldo":"5000000","tipo":"SaldoBloqueado","fecha":null,"indicador":null},{"monto":null,"saldo":"5000000","tipo":"Sobregiro","fecha":null,"indicador":null}]},"alias":{"tipo":"CI","alias":"4409003"}},{"estadoCuenta":{"estado":{"codigo":"AC","valor":"Activo","fecha":null},"tipoEstado":"Activa"},"identificacion":{"tipoIdentificadorCuenta":"NumeroCuenta","identificacion":{"codigo":"81-25","valor":"José Samaniego","fechaEmision":null,"fechaVencimiento":null}},"fecha":{"tipo":"FechaApertura","fecha":"04-01-2023"},"relacion":{"codigo":"E","valor":"Empresa","fecha":null},"producto":{"tipo":"CuentaCorriente","nombre":"Cuenta Corriente","codigo":"101"},"moneda":{"id":"GS","codigo":"6900"},"balance":{"saldos":[{"monto":null,"saldo":"5000000","tipo":"SaldoDisponible","fecha":null,"indicador":null},{"monto":null,"saldo":"5000000","tipo":"SaldoRetenido","fecha":null,"indicador":null},{"monto":null,"saldo":"5000000","tipo":"SaldoActual","fecha":null,"indicador":null},{"monto":null,"saldo":"5000000","tipo":"SaldoBloqueado","fecha":null,"indicador":null},{"monto":null,"saldo":"5000000","tipo":"Sobregiro","fecha":null,"indicador":null}]},"alias":{"tipo":"CI","alias":"4409003"}}]'
        
        '400':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/BadRequest'
        '401':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/Unauthorized'
        '403':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/Forbidden'
        '404':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/NotFound'
        '429':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/TooManyRequests'
        '500':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/InternalServerError'

  '/clientes/{codigo-cliente}/productos/cuentas/{codigo-cuenta}':
    get:
      tags:
        - cuentas
        - clientes
        - Get
      summary: Obtener detalles de una cuenta
      description: Obtiene todos los detalles de una cuenta en especifico, sus saldos y configuracion.
      operationId: get
      parameters:
        - $ref: './familiar-components-v1.0.0.yaml#/components/parameters/codigo-cliente'
        - $ref: './familiar-components-v1.0.0.yaml#/components/parameters/codigo-cuenta'
      responses:
        '200':
          description: 'Respuesta Cuenta Corriente'
          content:
            application/json:
              schema:
                $ref: '#/components/responses/CuentaResponse'
              examples:
                example:
                  value: '{"estadoCuenta":{"estado":{"codigo":"AC","valor":"Activo","fecha":null},"tipoEstado":"Activa"},"identificacion":{"tipoIdentificadorCuenta":"NumeroCuenta","identificacion":{"codigo":"81-25","valor":"José Samaniego","fechaEmision":null,"fechaVencimiento":null}},"fecha":{"tipo":"FechaApertura","fecha":"04-01-2023"},"relacion":{"codigo":"E","valor":"Empresa","fecha":null},"producto":{"tipo":"CuentaCorriente","nombre":"Cuenta Corriente","codigo":"101"},"moneda":{"id":"GS","codigo":"6900"},"balance":{"saldos":[{"monto":null,"saldo":"5000000","tipo":"SaldoDisponible","fecha":null,"indicador":null},{"monto":null,"saldo":"5000000","tipo":"SaldoRetenido","fecha":null,"indicador":null},{"monto":null,"saldo":"5000000","tipo":"SaldoActual","fecha":null,"indicador":null},{"monto":null,"saldo":"5000000","tipo":"SaldoBloqueado","fecha":null,"indicador":null},{"monto":null,"saldo":"5000000","tipo":"Sobregiro","fecha":null,"indicador":null}]},"alias":{"tipo":"CI","alias":"4409003"}}'
        '400':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/BadRequest'
        '401':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/Unauthorized'
        '403':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/Forbidden'
        '404':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/NotFound'
        '429':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/TooManyRequests'
        '500':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/InternalServerError'

  '/clientes/{codigo-cliente}/productos/cuentas/{codigo-cuenta}/movimientos':
    post:
      tags:
        - cuentas
        - clientes
        - movimientos
        - List
      summary: Moviemntos de una cuenta
      description: Obtiene todos los movimientos de una cuenta de un rango en especifico
      operationId: list
      parameters:
        - $ref: './familiar-components-v1.0.0.yaml#/components/parameters/codigo-cliente'
        - $ref: './familiar-components-v1.0.0.yaml#/components/parameters/codigo-cuenta'
      requestBody:
        $ref: '#/components/requestBodies/MovimientosCuentaRequest'
      responses:
        '200':
          $ref: '#/components/responses/MovimientoList'
        '400':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/BadRequest'
        '401':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/Unauthorized'
        '403':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/Forbidden'
        '404':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/NotFound'
        '429':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/TooManyRequests'
        '500':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/InternalServerError'

components:
  requestBodies:
    MovimientosCuentaRequest:
      content:
        application/json:
          schema:
            $ref: './familiar-components-v1.0.0.yaml#/components/schemas/MovimientosCuentaRequest'
      required: true

  responses:
    CuentaListarResponse:
      description: Listar Cuenta
      content:
        application/json:
          schema:
            $ref: './familiar-components-v1.0.0.yaml#/components/schemas/CuentaListar'
    CuentaResponse:
      description: Cuenta
      content:
        application/json:
          schema:
            $ref: './familiar-components-v1.0.0.yaml#/components/schemas/Cuenta'
    MovimientoList:
      description: Cuenta
      content:
        application/json:
          schema:
            $ref: './familiar-components-v1.0.0.yaml#/components/schemas/MovimientoList'

  examples:
    Cuenta:
      value:
        externalValue: './cuenta.json'


  securitySchemes:
    default:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'https://test.com'
          scopes: {}      
    