openapi: 3.0.1
info:
  title: Cotización de Divisas API
  description: API para obtener taza de cambios.
  contact:
    name: Banco Familiar
    email: 'desarrollo_bf@familiar.com.py'
  version: 1.0.0
servers:
  - url: https://api.example.com/v1
    description: Servidor principal (producción)
  - url: https://staging-api.example.com
    description: Servidor interno de pruebas
security:
  - default: []  
paths:
  /cotizacion/{codigoMoneda}:
    get:
      tags:
        - list
        - cambio
      summary: Tasa de cambio de todas las sucursales.
      description: Obtiene las tasas de cambio actuales de todas las sucursales desde una moneda base hacia otras monedas. 
      operationId: getCotizaciones
      parameters:
        - $ref: '#/components/parameters/monedaBase'
        - $ref: '#/components/parameters/fecha'
      responses:
        '200':
          $ref: '#/components/responses/monedaListar'
        '400':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/BadRequest'
        '401':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/Unauthorized'
        '403':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/Forbidden'
        '404':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/NotFound'
        '429':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/TooManyRequests'
        '500':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/InternalServerError'

  /cotizacion/{codigoMoneda}/sucursales/{sucursal}:
    get:
      tags:
        - list
        - cambio
      summary: Tasa de cambio de una sucursal
      description: Obtiene las tasas de cambio actuales de una sucursal desde una moneda base hacia otras monedas. 
      operationId: getCotizacionesSucursal
      parameters:
        - $ref: '#/components/parameters/monedaBase'
        - $ref: '#/components/parameters/sucursal'
        - $ref: '#/components/parameters/fecha'
      responses:
        '200':
          $ref: '#/components/responses/sucursalesListar'
        '400':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/BadRequest'
        '401':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/Unauthorized'
        '403':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/Forbidden'
        '404':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/NotFound'
        '429':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/TooManyRequests'
        '500':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/InternalServerError'

  /cotizacion/{codigoMoneda}/sucursales/{sucursal}/monedas/{codigoMoneda}:
    get:
      tags:
        - get
        - cambio     
      summary: Tasa de cambio de una moneda especifica en una sucursal.
      operationId: getCotizacionesSucursalMoneda
      description: Obtiene las tasas de cambio actual de una moneda de una sucursal desde una moneda base.
      parameters:
        - $ref: '#/components/parameters/monedaBase'
        - $ref: '#/components/parameters/sucursal'
        - $ref: '#/components/parameters/monedaBase'
        - $ref: '#/components/parameters/fecha'

      responses:
        '200':
          $ref: '#/components/responses/moneda'
        '400':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/BadRequest'
        '401':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/Unauthorized'
        '403':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/Forbidden'
        '404':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/NotFound'
        '429':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/TooManyRequests'
        '500':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/InternalServerError'


  '/cotizacion/{codigo-cliente}/prepactada':
    get:
      tags:
        - list
      summary: Obtiene las tasas de cambio prepactada con un cliente
      description: Devuelve las tasas de cambio prepactada de un cliente
      operationId: getCotizacioPrepactada
      parameters:
        - $ref: './familiar-components-v1.0.0.yaml#/components/parameters/codigo-cliente'

      responses:
        '200':
          $ref: '#/components/responses/movimientoListar'
        '400':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/BadRequest'
        '401':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/Unauthorized'
        '403':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/Forbidden'
        '404':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/NotFound'
        '429':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/TooManyRequests'
        '500':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/InternalServerError'
components:
  schemas:
    cotizaciones:
      type: object
      properties:
        cotizacion:
          type: array 
          items: 
            $ref: '#/components/schemas/moneda'

    moneda:
      allOf:
        - $ref: './familiar-components-v1.0.0.yaml#/components/schemas/accountcurrency'
        - type: object
          properties:
            compra:
              type: number
            venta:
              type: number

    sucursales:
      type: object
      properties:
        nombreSucursal:
          type: string
          description: Nombre de la sucursal
        cotizaciones:
          type: array 
          items: 
            $ref: '#/components/schemas/moneda'

    pizarra:
      type: object
      properties:
        monedaOrigen:
          type: string
        fecha:
          type: string
        sucursales:
          type: array 
          items: 
            $ref: '#/components/schemas/sucursales'
    
    movimiento:
      type: object
      properties:
        identificador:
          type: string
        codigoCliente:
          type: string
        monedaBase:
          type: string
        monedaDestino:
          type: string
        monto:
          type: string
        fecha:
          type: string
        estado:
          type: string

    movimientoListar:
      type: object
      properties:
        movimientos:
          type: array 
          items: 
            $ref: '#/components/schemas/movimiento'
  parameters:
    monedaBase:
      name: codigoMoneda
      in: path
      description: Codigo Moneda. Ejemplo GS.
      required: true
      style: simple
      schema:
        type: string
    fecha: 
      name: fecha
      in: query
      description: filtro por fecha del cambio. Por defecto es la cotización del día
      required: false
      schema:
        type: string
    sucursal:
      name: sucursal
      in: path
      required: true
      description: nombre de la sucursal
      schema:
        type: string
  responses:
    monedaListar:
      description: Moneda
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/pizarra'
    sucursalesListar:
      description: sucursal
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/sucursales'

    moneda:
      description: sucursal
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/moneda'   
    
    movimientoListar:
      description: lista de operaciones prepactadas
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/movimientoListar'  
  securitySchemes:
    default:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'https://test.com'
          scopes: {}       