openapi: 3.0.1
info:
  title: Gestión Deuda clientes
  description: API para obtener los seguimientos de gestores a clientes.
  contact:
    name: Banco Familiar
    email: 'desarrollo_bf@familiar.com.py'
  version: v1
servers:
  - url: https://api-test.familiar.com.py
    description: Servidor principal (producción)

security:
  - default: []  
paths:
  /clientes/{codigo-cliente}/cobranzas/gestores:
    get:
      summary: Gestor asignado
      description: Retorna los gestores asignados al cliente 
      operationId: getAllGestorCliente
      parameters:
        - $ref: './familiar-components-v1.0.0.yaml#/components/parameters/codigo-cliente'
      responses:
        '200':
          $ref: '#/components/responses/gestionDeuda'
        '400':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/BadRequest'
        '401':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/Unauthorized'
        '403':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/Forbidden'
        '404':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/NotFound'
        '422':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/UnprocessableEntity'
        '500':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/InternalServerError'
    
  /clientes/{codigo-cliente}/cobranzas/seguimiento:
    post:
      summary: registra un seguimiento a un cliente
      description: Registra un seguimiento para el cobro de la deuda de un cliente. 
      operationId: updateSeguimiento
      parameters:
        - $ref: './familiar-components-v1.0.0.yaml#/components/parameters/codigo-cliente'
      requestBody:
        $ref: '#/components/requestBodies/seguimientoRequest'
      responses:
        '200':
          $ref: '#/components/responses/seguimientosList'
        '400':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/BadRequest'
        '401':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/Unauthorized'
        '403':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/Forbidden'
        '404':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/NotFound'
        '422':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/UnprocessableEntity'
        '500':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/InternalServerError'
 
  /clientes/{codigo-cliente}/cobranzas/seguimientos:
    get:
      summary: seguimientos de cobro a un cliente
      description: Retorna los gestores asignados al cliente 
      operationId: getAllSeguimientosCliente
      parameters:
        - $ref: './familiar-components-v1.0.0.yaml#/components/parameters/codigo-cliente'
        - $ref: './familiar-components-v1.0.0.yaml#/components/parameters/fechaDesde'
        - $ref: './familiar-components-v1.0.0.yaml#/components/parameters/fechaHasta'
        - $ref: './familiar-components-v1.0.0.yaml#/components/parameters/limite'
        - $ref: './familiar-components-v1.0.0.yaml#/components/parameters/pagina'

      responses:
        '200':
          $ref: '#/components/responses/seguimientosList'
        '400':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/BadRequest'
        '401':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/Unauthorized'
        '403':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/Forbidden'
        '404':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/NotFound'
        '422':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/UnprocessableEntity'
        '500':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/InternalServerError' 
  
  /cobranzas/respuestas/etapas/{codigo-etapa}:
    get:
      summary: Respuestas por Etapa
      description: Retorna las respuestas que pueden registrarse por cada etapa de la gestión de la cobranza
      operationId: getAllRespuestasEtapa
      parameters:
         - $ref: './familiar-components-v1.0.0.yaml#/components/parameters/codigo-etapa'
      responses:
        '200':
          $ref: '#/components/responses/gestionRespuestas'
        '400':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/BadRequest'
        '401':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/Unauthorized'
        '403':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/Forbidden'
        '404':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/NotFound'
        '422':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/UnprocessableEntity'
        '500':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/InternalServerError'

  /cobranzas/contactos/operaciones/{codigo-sucursal}/{numero-operacion}:
    get:
      summary: Contactos por Operaciones
      description: Retorna los contactos de una operacion para la gestión de la cobranza
      operationId: getAllContactosOperaciones
      parameters:
         - $ref: './familiar-components-v1.0.0.yaml#/components/parameters/codigo-sucursal'
         - $ref: './familiar-components-v1.0.0.yaml#/components/parameters/numero-operacion'
      responses:
        '200':
          $ref: '#/components/responses/gestionContactos'
        '400':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/BadRequest'
        '401':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/Unauthorized'
        '403':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/Forbidden'
        '404':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/NotFound'
        '422':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/UnprocessableEntity'
        '500':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/InternalServerError'
components:
  schemas:
    seguimientos:
      type: object
      properties:
        metadata:
          $ref: './familiar-components-v1.0.0.yaml#/components/schemas/metadata'
        registros:
          type: array 
          items: 
            $ref: './familiar-components-v1.0.0.yaml#/components/schemas/evento'
    respuesta:
         allOf:
           - $ref: './familiar-components-v1.0.0.yaml#/components/schemas/codeValue'
           - type: object
             properties:
                codigoEtapa:
                  type: string
    seguimiento:
         allOf:
           - $ref: './familiar-components-v1.0.0.yaml#/components/schemas/evento'
           - $ref: './familiar-components-v1.0.0.yaml#/components/schemas/identification'
    identificacion:
         allOf:
           - $ref: './familiar-components-v1.0.0.yaml#/components/schemas/identification'
           - type: object
             properties:
                rol:
                  type: string
    referencia:
        type: object
        properties:
          cliente:  
            $ref: '#/components/schemas/identificacion' 
          contactos:
            type: array 
            items: 
             $ref: '#/components/schemas/contacto'
    contacto:
          type: object
          properties:
              tipo:  
                $ref: './familiar-components-v1.0.0.yaml#/components/schemas/contacttypevalues'
              valor:
                type: string

               
    respuestas:
       type: object
       properties:
          respuestas:
           type: array 
           items: 
             $ref: '#/components/schemas/respuesta'
    referencias:
         properties:
          referencias:
           type: array 
           items: 
             $ref: '#/components/schemas/referencia'
              
  requestBodies:
    
    seguimientoRequest:
      content:
        application/json:
          schema:
            $ref: './familiar-components-v1.0.0.yaml#/components/schemas/evento'
      required: true
  responses:
    gestionDeuda:
      description: tramo y gestor
      content:
        application/json:
          schema:
            $ref: './familiar-components-v1.0.0.yaml#/components/schemas/evento'
    
    seguimientosList:
      description: Lista los eventos de cobranzas realizado por un gestor al clientes.
      content:
        application/json:
          schema:
             $ref: '#/components/schemas/seguimientos'

    gestionRespuestas:
      description: Lista las respuestas por cada etapa de la gestión de cobranza.
      content:
        application/json:
          schema:
             $ref: '#/components/schemas/respuestas'

    gestionContactos:
      description: Lista los contactos por cada operacion de la gestión de cobranza.
      content:
        application/json:
          schema:
             $ref: '#/components/schemas/referencias'

    respuestaExistosa:
      description: actualizacion de seguimiento
      content:
        application/json:
          schema:
            $ref: './familiar-components-v1.0.0.yaml#/components/schemas/respuestaExitosa'

  securitySchemes:
    default:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'https://test.com'
          scopes: {}       