openapi: 3.0.1
info:
  title: Cotización de Divisas aplicacion
  description: API para obtener taza de cambios.
  contact:
    name: Banco Familiar
    email: 'desarrollo_bf@familiar.com.py'
  version: v1
servers:
  - url: https://api-test.familiar.com.py
security:
  - default: []  
paths:
  /cotizaciones/monedas/{codigoMoneda}:
    get:
      summary: Tasa de cambio de todas las sucursales.
      description: Obtiene las tasas de cambio actuales de todas las sucursales desde una moneda base hacia otras monedas. 
      operationId: getCotizaciones
      parameters:
        - $ref: '#/components/parameters/monedaBase'
        - $ref: '#/components/parameters/fecha'
      responses:
        '200':
          $ref: '#/components/responses/monedaListar'
        '400':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/BadRequest'
        '401':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/Unauthorized'
        '403':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/Forbidden'
        '404':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/NotFound'
        '422':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/UnprocessableEntity'
        '500':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/InternalServerError'

  /cotizaciones/monedas/{codigoMoneda}/sucursales/{sucursal}:
    get:
      summary: Tasa de cambio de una sucursal
      description: Obtiene las tasas de cambio actuales de una sucursal desde una moneda base hacia otras monedas. 
      operationId: getCotizacionesSucursal
      parameters:
        - $ref: '#/components/parameters/monedaBase'
        - $ref: '#/components/parameters/sucursal'
        - $ref: '#/components/parameters/fecha'
      responses:
        '200':
          $ref: '#/components/responses/sucursalesListar'
        '400':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/BadRequest'
        '401':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/Unauthorized'
        '403':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/Forbidden'
        '404':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/NotFound'
        '422':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/UnprocessableEntity'
        '500':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/InternalServerError'

  /cotizaciones/monedas{codigoMoneda}/sucursales/{sucursal}/monedasDestino/{codigoMonedaDestino}:
    get:    
      summary: Tasa de cambio de una moneda especifica en una sucursal.
      operationId: getCotizacionesSucursalMoneda
      description: Obtiene las tasas de cambio actual de una moneda de una sucursal desde una moneda base.
      parameters:
        - $ref: '#/components/parameters/monedaBase'
        - $ref: '#/components/parameters/sucursal'
        - $ref: '#/components/parameters/monedaDestino'
        - $ref: '#/components/parameters/fecha'

      responses:
        '200':
          $ref: '#/components/responses/moneda'
        '400':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/BadRequest'
        '401':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/Unauthorized'
        '403':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/Forbidden'
        '404':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/NotFound'
        '422':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/UnprocessableEntity'
        '500':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/InternalServerError'

components:
  schemas:
    moneda:
      allOf:
        - $ref: './familiar-components-v1.0.0.yaml#/components/schemas/accountcurrency'
        - type: object
          properties:
            compra:
              type: number
            venta:
              type: number
            tipoOperacion:
              $ref: './familiar-components-v1.0.0.yaml#/components/schemas/codeValue'

    sucursales:
      type: object
      properties:
        nombreSucursal:
          type: string
        codigoSucursal:
          type: string
        cotizaciones:
          type: array 
          items: 
            $ref: '#/components/schemas/moneda'

    pizarra:
      type: object
      properties:
        monedaOrigen:
          type: string
        fecha:
          type: string
        sucursales:
          type: array 
          items: 
            $ref: '#/components/schemas/sucursales'
    
  
  parameters:
    monedaBase:
      name: codigoMoneda
      in: path
      description: Codigo Moneda. Ejemplo GS.
      required: true
      style: simple
      schema:
        type: string
    monedaDestino:
      name: codigoMonedaDestino
      in: path
      description: Codigo Moneda. Ejemplo GS.
      required: true
      style: simple
      schema:
        type: string
    fecha: 
      name: fecha
      in: query
      description: filtro por fecha del cambio. Por defecto es la cotización del día
      required: false
      schema:
        type: string
    sucursal:
      name: sucursal
      in: path
      required: true
      description: nombre de la sucursal
      schema:
        type: string
  responses:
    monedaListar:
      description: Moneda
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/pizarra'
    sucursalesListar:
      description: sucursal
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/sucursales'

    moneda:
      description: moneda
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/moneda'   
    

  securitySchemes:
    default:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'https://test.com'
          scopes: {}       