openapi: 3.0.1
info:
  title: Clientes
  description: 'Este servicio obtiene datos relacioandos al Clientes, sus productos y servicios, movimientos y configuracion relacionada al cliente'
  contact:
    name: Banco Familiar
    email: 'desarrollo_bf@familiar.com.py'
  version: v1
servers:
  - url: https://api-test.familiar.com.py
security:
  - default: []    
paths:
  '/clientes/{codigo-cliente}/productos/cuentas':
    get:
      summary: Obtener lista de cuentas de un cliente
      description: Obtener informacion sobre todas las cuentas del clientes. Cajas de ahorro, cuentas corrientes, cuentas digitales, etc.
      operationId: getall
      parameters:
        - $ref: './familiar-components-v1.0.0.yaml#/components/parameters/codigo-cliente'
      responses:
        '200':
          $ref: '#/components/responses/cuentaListarResponse'
        '400':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/BadRequest'
        '401':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/Unauthorized'
        '403':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/Forbidden'
        '404':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/NotFound'
        '422':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/UnprocessableEntity'
        '500':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/InternalServerError'

  '/clientes/{codigo-cliente}/productos/cuentas/{codigo-cuenta}':
    get:
      summary: Obtener detalles de una cuenta
      description: Obtiene todos los detalles de una cuenta en especifico, sus saldos y configuracion.
      operationId: get
      parameters:
        - $ref: './familiar-components-v1.0.0.yaml#/components/parameters/codigo-cliente'
        - $ref: './familiar-components-v1.0.0.yaml#/components/parameters/codigo-cuenta'
      responses:
        '200':
          $ref: '#/components/responses/cuentaResponse'
        '400':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/BadRequest'
        '401':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/Unauthorized'
        '403':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/Forbidden'
        '404':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/NotFound'
        '422':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/UnprocessableEntity'
        '500':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/InternalServerError'

  '/clientes/{codigo-cliente}/productos/cuentas/{codigo-cuenta}/movimientos':
    post:
      summary: Moviemntos de una cuenta
      description: Obtiene todos los movimientos de una cuenta de un rango en especifico
      operationId: list
      parameters:
        - $ref: './familiar-components-v1.0.0.yaml#/components/parameters/codigo-cliente'
        - $ref: './familiar-components-v1.0.0.yaml#/components/parameters/codigo-cuenta'
      requestBody:
        $ref: '#/components/requestBodies/movimientosCuentaRequest'
      responses:
        '200':
          $ref: '#/components/responses/movimientoList'
        '400':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/BadRequest'
        '401':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/Unauthorized'
        '403':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/Forbidden'
        '404':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/NotFound'
        '422':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/UnprocessableEntity'
        '500':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/InternalServerError'

  '/clientes/{codigo-cliente}/servicios/cotizaciones/':
    get:
      summary: Obtiene las tasas de cambio prepactada con un cliente
      description: Devuelve las tasas de cambio prepactada de un cliente
      operationId: getCotizacioPrepactada
      parameters:
        - $ref: './familiar-components-v1.0.0.yaml#/components/parameters/codigo-cliente'

      responses:
        '200':
          $ref: '#/components/responses/prepactadoListar'
        '400':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/BadRequest'
        '401':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/Unauthorized'
        '403':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/Forbidden'
        '404':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/NotFound'
        '422':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/UnprocessableEntity'
        '500':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/InternalServerError'

components:
  requestBodies:
    movimientosCuentaRequest:
      content:
        application/json:
          schema:
            $ref: './familiar-components-v1.0.0.yaml#/components/schemas/paginadoRequest'
      required: true

  responses:
    cuentaListarResponse:
      description: Listar Cuenta
      content:
        application/json:
          schema:
            $ref: './familiar-components-v1.0.0.yaml#/components/schemas/cuentaListar'
    cuentaResponse:
      description: Cuenta
      content:
        application/json:
          schema:
            $ref: './familiar-components-v1.0.0.yaml#/components/schemas/cuenta'
    movimientoList:
      description: Cuenta
      content:
        application/json:
          schema:
            $ref: './familiar-components-v1.0.0.yaml#/components/schemas/movimientoList'
    prepactadoListar:
      description: lista de operaciones prepactadas
      content:
        application/json:
          schema:
            $ref: './familiar-components-v1.0.0.yaml#/components/schemas/prepactadoListar'  

  securitySchemes:
    default:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'https://test.com'
          scopes: {}      
    