openapi: 3.0.1
info:
  title: Gestión Deuda clientes
  description: API para obtener los seguimientos de gestores a clientes.
  contact:
    name: Banco Familiar
    email: 'desarrollo_bf@familiar.com.py'
  version: v1
servers:
  - url: https://api-test.familiar.com.py
    description: Servidor principal (producción)

security:
  - default: []  
paths:

  /cobranzas/respuestas/etapas/{codigoEtapa}:
    get:
      summary: Respuestas por Etapa
      description: Retorna las respuestas que pueden registrarse por cada etapa de la gestión de la cobranza
      operationId: getAllRespuestasEtapa
      parameters:
         - $ref: './familiar-components-v1.0.0.yaml#/components/parameters/codigoEtapa'
      responses:
        '200':
          $ref: '#/components/responses/gestionRespuestas'
        '400':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/BadRequest'
        '401':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/Unauthorized'
        '403':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/Forbidden'
        '404':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/NotFound'
        '422':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/UnprocessableEntity'
        '500':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/InternalServerError'

  /cobranzas/contactos/operaciones/{codigoSucursal}/{numeroOperacion}:
    get:
      summary: Contactos por Operaciones
      description: Retorna los contactos de una operacion para la gestión de la cobranza
      operationId: getAllContactosOperaciones
      parameters:
         - $ref: './familiar-components-v1.0.0.yaml#/components/parameters/codigoSucursal'
         - $ref: './familiar-components-v1.0.0.yaml#/components/parameters/numeroOperacion'
      responses:
        '200':
          $ref: '#/components/responses/gestionContactos'
        '400':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/BadRequest'
        '401':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/Unauthorized'
        '403':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/Forbidden'
        '404':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/NotFound'
        '422':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/UnprocessableEntity'
        '500':
          $ref: './familiar-components-v1.0.0.yaml#/components/responses/InternalServerError'
  
components:
  schemas:

    respuesta:
         allOf:
           - $ref: './familiar-components-v1.0.0.yaml#/components/schemas/codeValue'
           - type: object
             properties:
                codigoEtapa:
                  type: string
    seguimiento:
         allOf:
           - $ref: './familiar-components-v1.0.0.yaml#/components/schemas/evento'
           - $ref: './familiar-components-v1.0.0.yaml#/components/schemas/identification'
    identificacion:
         allOf:
           - $ref: './familiar-components-v1.0.0.yaml#/components/schemas/identification'
           - type: object
             properties:
                rol:
                  type: string

    referencia:
        type: object
        properties:
          cliente:  
            $ref: '#/components/schemas/identificacion' 
          contactos:
            type: array 
            items: 
             $ref: '#/components/schemas/contacto'

        
    contacto:
          type: object
          properties:
              tipo:  
                $ref: './familiar-components-v1.0.0.yaml#/components/schemas/contacttypevalues'
              valor:
                type: string
    respuestas:
       type: object
       properties:
          respuestas:
           type: array 
           items: 
             $ref: '#/components/schemas/respuesta'
    referencias:
         properties:
          referencias:
           type: array 
           items: 
             $ref: '#/components/schemas/referencia'

    
              
  
    

  responses:
   
    


    gestionRespuestas:
      description: Lista las respuestas por cada etapa de la gestión de cobranza.
      content:
        application/json:
          schema:
             $ref: '#/components/schemas/respuestas'

    gestionContactos:
      description: Lista los contactos por cada operacion de la gestión de cobranza.
      content:
        application/json:
          schema:
             $ref: '#/components/schemas/referencias'

  securitySchemes:
    default:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'https://test.com'
          scopes: {}       